config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'admin/index'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :news_items

  get 'say/hello'

  get 'say/goodbye'

  get 'say/photos'

  root 'say#hello'

end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  validates :published_on, :content, :image_url, presence: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
}
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end    
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_news_items = NewsItem.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    # ...

  protected

    def authorize
      unless User.find_by(id: session[:user_id])
        redirect_to login_url, notice: "Please log in"
      end
    end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_action :set_news_item, only: [:show, :edit, :update, :destroy]

  # GET /news_items
  # GET /news_items.json
  def index
    @news_items = NewsItem.all
  end

  # GET /news_items/1
  # GET /news_items/1.json
  def show
  end

  # GET /news_items/new
  def new
    @news_item = NewsItem.new
    @news_item.image_url = "https://s3.amazonaws.com/robhughesdotnet/gallery/website/NothingToSeeHere.png"
  end

  # GET /news_items/1/edit
  def edit
  end

  # POST /news_items
  # POST /news_items.json
  def create
    @news_item = NewsItem.new(news_item_params)

    respond_to do |format|
      if @news_item.save
        format.html { redirect_to @news_item, notice: 'News item was successfully created.' }
        format.json { render :show, status: :created, location: @news_item }
      else
        format.html { render :new }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_items/1
  # PATCH/PUT /news_items/1.json
  def update
    respond_to do |format|
      if @news_item.update(news_item_params)
        format.html { redirect_to @news_item, notice: 'News item was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_item }
      else
        format.html { render :edit }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_items/1
  # DELETE /news_items/1.json
  def destroy
    @news_item.destroy
    respond_to do |format|
      format.html { redirect_to news_items_url, notice: 'News item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_item
      @news_item = NewsItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_item_params
      params.require(:news_item).permit(:content, :published_on, :image_url)
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  skip_before_action :authorize

  def hello
    #@news_items = NewsItem.order(:published_on)
    @news_items = NewsItem.order(published_on: :desc)
  end

  def photos
  end

  def goodbye
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize

  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully created." }
        format.json { render action: 'show',
          status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted"
    rescue StandardError => e
      flash[:notice] = e.message
    end
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_news_items, "news_item") %>.

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
<!-- START_HIGHLIGHT -->
  <title>RobHughes.net</title>
<!-- END_HIGHLIGHT -->
  <!-- <label id="code.slt"/> --><%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %><!-- <label id="code.jlt"/> -->
  <%= csrf_meta_tags %><!-- <label id="code.csrf"/> -->
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START_HIGHLIGHT -->
<div id="outer">
  <div id="upbg"></div>

  <div id="inner">
  
    <div id="header">
      <h1>robhughes.net<sup>2.0</sup></h1>
      <br>
      <h2>...a work in progress</h2>
    </div>

    <div id="splash"></div>
   
    <div id="menu">
      <ul>
        <li> <%= link_to "Home", root_path %></li>
        <li> <%= link_to "Photos", say_photos_path %></li>
        <% if session[:user_id] %>
          <li><%= link_to 'News Items', news_items_path %></li>
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% end %>
      </ul>
<!--
      <% if session[:user_id] %>
        <%= button_to 'Logout', logout_path, method: :delete %>
      <% end %>
-->
      <div id="date"><%= Time.now.strftime("%A %B #{Time.now.day.ordinalize} %Y") %></div>
    </div> <!-- menu -->
  </div> <!-- inner -->
    
  <div id="main">
    <%= yield %>
  </div> <!-- main -->
</div> <!-- outer --> 
</body>
</html>

app/views/news_items/_form.html.erb
<%= form_for(@news_item) do |f| %>
  <% if @news_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_item.errors.count, "error") %> prohibited this news_item from being saved:</h2>

      <ul>
      <% @news_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, rows: 10 %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br>
    <%= f.date_select :published_on %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_items/edit.html.erb
<h1>Editing news_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_item %> |
<%= link_to 'Back', news_items_path %>

app/views/news_items/index.html.erb
<h1>Listing news items</h1>

<table>
<% @news_items.each do |news_item| %>
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

<td class="list_published_on">
<dl>
<dd><%= news_item.published_on %></dd>
</dl>
</td>
<td>
<%= image_tag(news_item.image_url, class: 'list_image') %>
</td>
<td class="list_content">
<dl>
<dd><%= truncate(strip_tags(news_item.content),
length: 80) %></dd>
</dl>
</td>
<td class="list_actions">
<%= link_to 'Show', news_item %><br/>
<%= link_to 'Edit', edit_news_item_path(news_item) %><br/>
<%= link_to 'Destroy', news_item, method: :delete,
data: { confirm: 'Are you sure?' } %>
</td>
</tr>
<% end %>
</table>
<br />

<%= link_to 'New News item', new_news_item_path %>

app/views/news_items/new.html.erb
<h1>New news_item</h1>

<%= render 'form' %>

<%= link_to 'Back', news_items_path %>

app/views/news_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @news_item.content %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @news_item.published_on %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @news_item.image_url %>
</p>

<%= link_to 'Edit', edit_news_item_path(@news_item) %> |
<%= link_to 'Back', news_items_path %>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

app/views/say/hello.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h3>What's New:</h3>

<% @news_items.each do |news_item| %>
<div class="entry">
<%= image_tag(news_item.image_url) %>
<h3><%= news_item.published_on %></h3>
<%= sanitize(news_item.content) %>
</div>
<% end %>

app/views/say/photos.html.erb
		<div id="primarycontent">

			<!-- primary content start -->

			<div class="post">
				<div class="header">
					<h3>Photo Gallery</h3>
				</div>
				

				<div class="content">
       			 	<LI><A HREF="/gallery/2003CaymanBrac/RobsPictures/index.html">Cayman Brac 2003</A>
   					<LI><A HREF="/gallery/2003OldRagHike/index.html">Old Rag Hike 2003</A>
   					<LI><A HREF="/gallery/2004LakeTahoe/index.html">Tahoe 2004</A>
                	<LI><A HREF="/gallery/2008_Colorado/album/index.html">Colorado 2008</A>
                	<LI><A HREF="/gallery/2009_Colorado/2009_Colorado/album/index.html">Colorado 2009</A>

					<br><br><em>Germany 2011 Trip</em><br>
					<LI><A HREF="/gallery/2011Germany/Drive%20To%20Garmisch/album/index.html">Drive to Garmisch</A>
					<LI><A HREF="/gallery/2011Germany/Linderhof%20Palace/album/index.html">Linderhof Palace</A>
					<LI><A HREF="/gallery/2011Germany/Berchtesgaden%20Tour/album/index.html">Berchtesgaden Tour</A>
					<LI><A HREF="/gallery/2011Germany/Three%20Country%20Tour/album/index.html">Three Country Tour</A>
					<LI><A HREF="/gallery/2011Germany/Bolzano%20Italy%20Tour/album/index.html">Bolzano Italy Tour</A>
					<LI><A HREF="/gallery/2011Germany/Partnach%20Gorge/album/index.html">Partnach Gorge</A>
					<LI><A HREF="/gallery/2011Germany/Drive%20to%20Schweinfurt/album/index.html">Drive to Schweinfurt</A>
                      <br><br>
					<LI><A HREF="/gallery/2011%20Fruita%20CO%20Moab%20UT%20Mountain%20Bike%20Trip/album/index.html">Fruita and Moab 2011</A>
                      <br><br>
					<LI><A HREF="http://www.goldmishpacha.com/Vacation/Mans-Trip-Colorado-2015/n-drJfTf">Hiking Colorado 2015</A>
                      <br><br>
					<LI><A HREF="https://goo.gl/photos/S67s11K41TrqXW5w7">Florida Trip 2016</A>
					<br><br><em>South Carolina Trip 2019</em><br>
					<LI><A HREF="https://photos.app.goo.gl/nPZEf7njnf3eG44r6">Charleston, Liberty Square, and Ft. Sumter</A>
					<LI><A HREF="https://photos.app.goo.gl/hXnETxjJCdX5jE7P8">Patriot's Point</A>
                                        <LI><A HREF="https://photos.app.goo.gl/DkaSLdH9fpmGBqsR9">Isle of Palms</A>
                                        <LI><A HREF="https://photos.app.goo.gl/WG9dLd7HksKb1SaZA">Bull's Island Hike</A>
                                        <LI><A HREF="https://photos.app.goo.gl/oxTFf3aJdFfEoMnbA">Center for the Birds Of Prey</A>
                                        <LI><A HREF="https://photos.app.goo.gl/h4iPJ2VjzXQwmqkAA">Ft. Moultrie</A>

				</div>			
			</div>
		
			<!-- primary content end -->
	
		</div>

app/views/users/_form.html.erb
<div class="depot_form">

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter User Details</legend>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  </fieldset>
<% end %>

</div> <!-- depot_form -->

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>